"""empty message

Revision ID: 0149814d197d
Revises: 
Create Date: 2018-10-22 18:19:47.585401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0149814d197d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention',
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('intervention_name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('intervention_id'),
    sa.UniqueConstraint('intervention_id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fname', sa.String(length=140), nullable=True),
    sa.Column('lname', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_patient_username'), 'patient', ['username'], unique=True)
    op.create_table('therapist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fname', sa.String(length=140), nullable=True),
    sa.Column('lname', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_therapist_username'), 'therapist', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapist_username'), table_name='therapist')
    op.drop_table('therapist')
    op.drop_index(op.f('ix_patient_username'), table_name='patient')
    op.drop_table('patient')
    op.drop_table('intervention')
    # ### end Alembic commands ###
