"""session table

Revision ID: e6ec8b45ed18
Revises: b48e9c727ff5
Create Date: 2018-11-16 12:47:34.657872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ec8b45ed18'
down_revision = 'b48e9c727ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('gametype', sa.String(length=140), nullable=True),
    sa.Column('date_started', sa.String(length=140), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.intervention_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
